# Generated by Django 3.0.5 on 2020-04-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avtorization', '0003_auto_20200430_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
